import Link from 'next/link'
import { prisma } from '@/lib/db'
import { canWrite, requireAuth } from '@/lib/auth'
import { andVisibleInvoice } from '@/lib/invoice-visibility'
import { formatCurrency, formatDate } from '@/lib/format'
import { PageHeader } from '@/components/PageHeader'
import { InvoiceCostBar } from '@/components/InvoiceCostBar'
import { getInvoiceCostData } from '@/lib/costs/profitability-data'
import { suggestInvoicePeriod } from '@/lib/costs/invoice-association'
import { AnalysisForm } from './AnalysisForm'
import { saveInvoiceAssociation, saveExpenseAllocation, allocateSubscription, removeInvoiceAssociation } from './actions'
const input='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm'
const section='rounded-2xl border border-slate-200 bg-white p-5 sm:p-6'
const date=(d:Date)=>d.toISOString().slice(0,10)
function Field({label,children}:{label:string;children:React.ReactNode}) {return <label className="block space-y-1 text-sm font-medium text-slate-700"><span>{label}</span>{children}</label>}
export default async function AnalysisPage({searchParams}:{searchParams:{year?:string;invoice?:string;expense?:string}}){
 const user=await requireAuth(),writable=canWrite(user)
 const currentYear=new Date().getUTCFullYear(),year=/^20\d{2}$/.test(searchParams.year||'')?Number(searchParams.year):currentYear
 const start=new Date(Date.UTC(year,0,1)),end=new Date(Date.UTC(year+1,0,1))
 const [costData,projects,invoices,expenses,payments,credits,accounts]=await Promise.all([
  getInvoiceCostData(),prisma.costProject.findMany({where:{archived:false},include:{client:true},orderBy:{name:'asc'}}),
  prisma.invoice.findMany({where:andVisibleInvoice({status:{notIn:['draft','cancelled']}}),include:{client:true,items:true,creditNotes:true},orderBy:{issueDate:'desc'}}),
  prisma.expense.findMany({where:{isArchived:false},include:{costAllocations:{include:{project:true}}},orderBy:{date:'desc'}}),
  prisma.payment.findMany({where:{date:{gte:start,lt:end},OR:[{invoiceId:null},{invoice:{viewHidden:false}}]}}),
  prisma.creditNote.findMany({where:{issueDate:{gte:start,lt:end},status:{notIn:['draft','cancelled','void']},invoice:{viewHidden:false,status:{notIn:['draft','cancelled']}}},include:{client:true}}),
  prisma.costUsageEvent.findMany({where:{provider:'cursor'},select:{accountRef:true},distinct:['accountRef']})
 ])
 const issued=invoices.filter(i=>i.issueDate>=start&&i.issueDate<end),spent=expenses.filter(e=>e.date>=start&&e.date<end)
 const netRevenue=issued.reduce((n,i)=>n+i.total-i.vatTotal,0)-credits.reduce((n,c)=>n+c.total-c.vatTotal,0)
 const spending=spent.reduce((n,e)=>n+e.netAmount,0),cash=payments.reduce((n,p)=>n+(p.isRefund?-Math.abs(p.amount):p.amount),0)
 const selectedInvoice=invoices.find(i=>i.id===searchParams.invoice)||invoices[0]
 const selectedExpense=expenses.find(e=>e.id===searchParams.expense)||expenses[0]
 const association=costData.associations.find(a=>a.invoiceId===selectedInvoice?.id)
 const suggestion=selectedInvoice?suggestInvoicePeriod(selectedInvoice.items.map(i=>i.description).join('\n')):null
 const candidateProjects=projects.filter(p=>p.clientId===selectedInvoice?.clientId)
 const months=Array.from({length:12},(_,month)=>{
  const revenue=issued.filter(i=>i.issueDate.getUTCMonth()===month).reduce((n,i)=>n+i.total-i.vatTotal,0)-credits.filter(c=>c.issueDate.getUTCMonth()===month).reduce((n,c)=>n+c.total-c.vatTotal,0)
  const expense=spent.filter(e=>e.date.getUTCMonth()===month).reduce((n,e)=>n+e.netAmount,0)
  return {month:new Date(Date.UTC(year,month,1)).toLocaleDateString('en-GB',{month:'short',timeZone:'UTC'}),revenue,expense}
 })
 const max=Math.max(1,...months.flatMap(m=>[Math.abs(m.revenue),Math.abs(m.expense)]))
 const clientRows=Array.from(new Map([...issued.map(i=>[i.clientId,i.client] as const),...credits.map(c=>[c.clientId,c.client] as const)]).values()).map(client=>{
  const rows=issued.filter(i=>i.clientId===client.id),revenue=rows.reduce((n,i)=>n+i.total-i.vatTotal,0)-credits.filter(c=>c.clientId===client.id).reduce((n,c)=>n+c.total-c.vatTotal,0)
  const linked=rows.filter(i=>costData.associations.some(a=>a.invoiceId===i.id))
  const cost=linked.reduce((n,i)=>{const c=costData.costs.get(i.id);return n+(c?.direct||0)+(c?.subscription||0)},0)
  return {client,revenue,cost,linked:linked.length,total:rows.length}
 })
 const provisional=costData.allocations.some(a=>a.note.startsWith('Provisional'))
 const incomplete=costData.unallocatedCount>0||provisional
 return <div className="space-y-6">
 <PageHeader title="Costs & performance" description="Understand business spending, client contribution and the costs behind each invoice."/>
 <form className="flex items-end gap-3"><Field label="Reporting year"><input className={input} name="year" type="number" min="2000" max="2099" defaultValue={year}/></Field><button className="inline-flex min-h-10 items-center justify-center rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 disabled:cursor-wait disabled:opacity-50">Apply year</button></form>
 <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950">All figures are GBP. Revenue and expenses below exclude recorded VAT; receipts include VAT and are shown separately. Imported foreign bills use their recorded GBP conversion, which may differ from bank settlement. These are management estimates, before tax and owner labour.</div>
 <dl className="grid gap-px overflow-hidden rounded-2xl border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{[['Net invoiced',netRevenue],['Recorded expenses',spending],['Net after expenses',netRevenue-spending],['Cash received (incl. VAT)',cash]].map(([label,value])=><div key={label} className="bg-white p-5"><dt className="text-sm text-slate-600">{label}</dt><dd className="mt-2 text-2xl font-semibold tabular-nums">{formatCurrency(Number(value))}</dd></div>)}</dl>
 <section className={section}><h2 className="text-lg font-semibold">Business trend · {year}</h2><p className="mt-1 text-sm text-slate-600">Blue: invoices less credit notes, by document date. Rose: recorded expenses by expense date. Expense allocations do not add spending again.</p>
 <div className="mt-5 space-y-3" role="img" aria-label={`Monthly net invoiced revenue and recorded expenses for ${year}. Exact amounts follow in the table.`}>{months.map(m=><div key={m.month} className="grid grid-cols-[2rem_1fr] items-center gap-3"><span className="text-xs text-slate-600">{m.month}</span><div className="space-y-1"><div className="h-2 rounded-r bg-blue-600" style={{width:`${Math.abs(m.revenue)/max*100}%`}}/><div className="h-2 rounded-r bg-rose-400" style={{width:`${Math.abs(m.expense)/max*100}%`}}/></div></div>)}</div>
 <p className="mt-3 text-xs text-slate-500">Bars show magnitude; negative credits/refunds retain their sign in the table.</p><details className="mt-4"><summary className="cursor-pointer text-sm font-medium text-blue-700">View monthly figures</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Month</th><th>Net invoiced</th><th>Expenses</th><th>Difference</th></tr></thead><tbody>{months.map(m=><tr key={m.month} className="border-t border-slate-100"><th className="p-2 text-left font-medium">{m.month}</th><td className="text-right">{formatCurrency(m.revenue)}</td><td className="text-right">{formatCurrency(m.expense)}</td><td className="text-right">{formatCurrency(m.revenue-m.expense)}</td></tr>)}</tbody></table></div></details></section>
 <section className={section}><h2 className="text-lg font-semibold">Client contribution</h2><p className="mt-1 text-sm text-slate-600">Costs allocated to this year’s issued invoices, using their confirmed service periods. Shared service days are split by original net invoice value, before credit notes. Credits reduce revenue without erasing the cost of work. This is not a final profit calculation.</p>
 <div className="my-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{costData.unallocatedCount} expenses still have unallocated shares ({formatCurrency(costData.unallocatedPence)} net across all years). {provisional?'Usage-based subscription shares are provisional. ':''}{costData.invalidAllocationCount>0?`${costData.invalidAllocationCount} expense allocations no longer match their edited bill and have been excluded. Review their shares. `:''}Unassigned spending and internal overhead are not silently charged to clients.</div>
 <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="text-left text-slate-600"><th className="py-3">Client</th><th>Net invoiced</th><th>Allocated cost</th><th>Cost / revenue</th><th>Contribution</th><th>Coverage</th></tr></thead><tbody>{clientRows.map(r=><tr key={r.client.id} className="border-t border-slate-100"><th className="py-3 pr-3 text-left font-medium">{r.client.name}</th><td>{formatCurrency(r.revenue)}</td><td>{r.linked?formatCurrency(r.cost):'Not allocated'}</td><td>{r.linked&&r.revenue>0?`${(r.cost/r.revenue*100).toFixed(1)}%`:'—'}</td><td>{r.linked?formatCurrency(r.revenue-r.cost):'—'}{r.linked&&(incomplete||r.linked<r.total)?' *':''}</td><td>{r.linked}/{r.total} invoices linked{incomplete?' · partial':''}</td></tr>)}</tbody></table></div>{!clientRows.length&&<p className="py-4 text-sm text-slate-600">No issued invoices in this year.</p>}<p className="mt-3 text-xs text-slate-500">* Provisional contribution: missing allocations can overstate it. {formatCurrency(costData.unmatchedPence)} of project cost shares currently falls outside linked invoice periods (all years).</p></section>
 <section id="invoice-links" className={`${section} scroll-mt-6`}><h2 className="text-lg font-semibold">Connect invoices to their work</h2><p className="mt-1 text-sm text-slate-600">Confirm the project and service dates. A description-based suggestion is never applied until you save. Multi-project invoices need a reviewed split before they can be represented here.</p>
 <form className="my-4 flex flex-col items-end gap-3 sm:flex-row"><input type="hidden" name="year" value={year}/><div className="w-full"><Field label="Invoice"><select name="invoice" className={input} defaultValue={selectedInvoice?.id}>{invoices.map(i=><option key={i.id} value={i.id}>{i.invoiceNumber} · {i.client.name} · {formatCurrency(i.total)}</option>)}</select></Field></div><button className="inline-flex min-h-10 items-center justify-center rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 whitespace-nowrap">Review invoice</button></form>
 {selectedInvoice&&<><div className="mb-4 rounded-lg bg-slate-50 p-3 text-sm"><p className="font-medium">{selectedInvoice.invoiceNumber} · {selectedInvoice.client.name}</p><ul className="mt-2 space-y-1 text-slate-600">{selectedInvoice.items.map(i=><li key={i.id}>{i.description}</li>)}</ul><InvoiceCostBar invoiceId={selectedInvoice.id} netPence={selectedInvoice.total-selectedInvoice.vatTotal-selectedInvoice.creditNotes.filter(c=>!['draft','cancelled','void'].includes(c.status)).reduce((n,c)=>n+c.total-c.vatTotal,0)} cost={costData.costs.get(selectedInvoice.id)} associated={!!association} incomplete={incomplete}/></div>
 {writable&&<AnalysisForm key={selectedInvoice.id} action={saveInvoiceAssociation} label="Save invoice link"><input type="hidden" name="invoiceId" value={selectedInvoice.id}/><div className="grid gap-3 sm:grid-cols-3"><Field label="Project"><select required name="projectId" className={input} defaultValue={association?.projectId||(candidateProjects.length===1?candidateProjects[0].id:'')}><option value="">Choose project</option>{candidateProjects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Service starts"><input required type="date" name="start" className={input} defaultValue={association?date(association.periodStart):suggestion?.start}/></Field><Field label="Service ends (inclusive)"><input required type="date" name="end" className={input} defaultValue={association?date(association.periodEnd):suggestion?.end}/></Field></div>{suggestion&&!association&&<p className="text-sm text-blue-800">Suggested dates from “{suggestion.evidence}”. Check the full description before saving.</p>}{!candidateProjects.length&&<p className="text-sm text-amber-800">First link a project to {selectedInvoice.client.name} in <Link className="underline" href="/costs/projects">Projects & rates</Link>.</p>}<Field label="Evidence / reason"><input required maxLength={1000} name="note" className={input} defaultValue={association?.note||(suggestion?`Confirmed description: ${suggestion.evidence}`:'')}/></Field></AnalysisForm>}{writable&&association&&<div className="mt-4 border-t border-slate-100 pt-4"><AnalysisForm action={removeInvoiceAssociation} label="Remove invoice link"><input type="hidden" name="invoiceId" value={selectedInvoice.id}/></AnalysisForm></div>}</>}
 </section>
 <section id="allocations" className={`${section} scroll-mt-6`}><h2 className="text-lg font-semibold">Allocate actual bills</h2><p className="mt-1 text-sm text-slate-600">Use the existing expense once. Allocate its net amount across projects; leave internal overhead and unknown shares unallocated. Provider usage records are supporting evidence, never a second expense.</p>
 <form className="my-4 flex flex-col items-end gap-3 sm:flex-row"><input type="hidden" name="year" value={year}/><div className="w-full"><Field label="Expense or refund"><select name="expense" className={input} defaultValue={selectedExpense?.id}>{expenses.map(e=><option key={e.id} value={e.id}>{formatDate(e.date)} · {e.supplier||e.description} · {formatCurrency(e.netAmount)} net</option>)}</select></Field></div><button className="inline-flex min-h-10 items-center justify-center rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 whitespace-nowrap">Review expense</button></form>
 {selectedExpense&&<><div className="mb-4 rounded-lg bg-slate-50 p-3 text-sm"><p className="font-medium">{selectedExpense.description}</p><p className="mt-1">Net {formatCurrency(selectedExpense.netAmount)} · Remaining {formatCurrency(selectedExpense.netAmount-selectedExpense.costAllocations.reduce((n,a)=>n+a.amountPence,0))}</p><details className="mt-2"><summary className="cursor-pointer text-blue-700">Source notes</summary><p className="mt-2 whitespace-pre-wrap break-words text-slate-600">{selectedExpense.notes||'No source notes recorded.'}</p></details></div>
 {selectedExpense.costAllocations.map(a=><details key={a.id} className="mb-3 rounded-lg border border-slate-200 p-3"><summary className="cursor-pointer text-sm font-medium">{a.project.name} · {formatCurrency(a.amountPence)} · {a.kind}</summary><p className="my-3 text-sm text-slate-600">{formatDate(a.periodStart)} – {formatDate(a.periodEnd)} · {a.note}</p>{writable&&<AnalysisForm action={saveExpenseAllocation} label="Update share"><input type="hidden" name="expenseId" value={selectedExpense.id}/><input type="hidden" name="projectId" value={a.projectId}/><input type="hidden" name="kind" value={a.kind}/><div className="grid gap-3 sm:grid-cols-3"><Field label="Net GBP (0 removes share)"><input className={input} required name="amount" defaultValue={(a.amountPence/100).toFixed(2)} inputMode="decimal"/></Field><Field label="Service starts"><input className={input} required name="start" type="date" defaultValue={date(a.periodStart)}/></Field><Field label="Service ends"><input className={input} required name="end" type="date" defaultValue={date(a.periodEnd)}/></Field></div><Field label="Evidence / reason"><input className={input} required name="note" maxLength={1000} defaultValue={a.note}/></Field></AnalysisForm>}</details>)}
 {writable&&<><details className="mt-4" open><summary className="cursor-pointer font-medium text-blue-800">Add a reviewed project share</summary><div className="mt-4"><AnalysisForm key={selectedExpense.id} action={saveExpenseAllocation} label="Save project share"><input type="hidden" name="expenseId" value={selectedExpense.id}/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="Project"><select className={input} required name="projectId" defaultValue=""><option value="">Choose project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Cost type"><select className={input} name="kind"><option value="direct">Direct provider / other cost</option><option value="subscription">Subscription share</option></select></Field><Field label="Net GBP amount"><input className={input} required name="amount" inputMode="decimal" placeholder="0.00"/></Field><Field label="Service starts"><input className={input} required name="start" type="date"/></Field><Field label="Service ends (inclusive)"><input className={input} required name="end" type="date"/></Field></div><Field label="Evidence / reason"><input className={input} required name="note" maxLength={1000}/></Field></AnalysisForm></div></details>
 <details className="mt-5 border-t border-slate-200 pt-4"><summary className="cursor-pointer font-medium text-blue-800">Allocate a Cursor subscription using included usage</summary><p className="my-3 text-sm text-slate-600">For the subscription fee only, not a combined bill with on-demand charges. The entered period must match the bill. Shares use included nominal usage across this account, including internal and unassigned usage. Incomplete imports can bias the result; shares remain explicitly provisional.</p><AnalysisForm key={`usage-${selectedExpense.id}`} action={allocateSubscription} label="Create provisional shares"><input type="hidden" name="expenseId" value={selectedExpense.id}/><div className="grid gap-3 sm:grid-cols-3"><Field label="Cursor account"><select className={input} required name="accountRef" defaultValue=""><option value="">Choose account</option>{accounts.map(a=><option key={a.accountRef} value={a.accountRef}>{a.accountRef}</option>)}</select></Field><Field label="Billing period starts"><input className={input} required type="date" name="start"/></Field><Field label="Billing period ends"><input className={input} required type="date" name="end"/></Field></div><label className="flex items-start gap-2 text-sm text-slate-700"><input className="mt-1" required type="checkbox" name="acknowledge" value="yes"/>This expense is a subscription-only fee or refund. I understand imported usage may not cover the whole billing cycle and will review the shares.</label></AnalysisForm></details></>}
 </>}
 </section></div>
}
