import Link from 'next/link'
import { canWrite, requireAuth } from '@/lib/auth'
import { PageHeader } from '@/components/PageHeader'
import { ledger } from '@/lib/costs/service'
import { ledgerFx, convertUnits, formatGbpUnits } from '@/lib/costs/fx'
import { unitsText } from '@/lib/costs/money'
import { aggregateCostReport } from '@/lib/costs/report-aggregation'
import { buttonClass, inputClass, panel } from './ui'
import { RefreshFigures } from './RefreshFigures'
import { CollectorCoverage } from './CollectorCoverage'
import { CsvCoverage } from './CsvCoverage'
import { LegacyCharges } from './LegacyCharges'
import { CostReportCharts } from './CostReportCharts'
import { AnalysisForm } from './analysis/AnalysisForm'
import { retainReferenceRates } from './fx-actions'

export const dynamic = 'force-dynamic'
export default async function CostsPage({ searchParams }: { searchParams: { month?: string; project?: string; page?: string; legacyPage?: string } }) {
  const user = await requireAuth()
  const data = await ledger(searchParams.month, searchParams.project)
  const fx = await ledgerFx(data.rows)
  const rows = data.rows.map((r, i) => ({ ...r, quote: fx.quotes[i], nominalGbp: convertUnits(r.revision?.nominalUnits ?? null, fx.quotes[i]), cashGbp: convertUnits(r.revision?.providerUnits ?? null, fx.quotes[i]), chargeGbp: convertUnits(r.charge, fx.quotes[i]) }))
  const report = aggregateCostReport(rows.map(r => ({
    date: r.event.occurredAt.toISOString().slice(0, 10), projectId: r.event.projectId, projectName: r.event.project?.name ?? 'Unassigned',
    conversationId: r.event.conversationId,
    taskTopics: (() => { const evidence = r.revision?.evidence; if (!evidence || typeof evidence !== 'object' || Array.isArray(evidence)) return []; const context = (evidence as Record<string, unknown>).taskContext; if (!context || typeof context !== 'object' || Array.isArray(context)) return []; const topics = (context as Record<string, unknown>).topics; return Array.isArray(topics) ? topics.filter((topic): topic is string => typeof topic === 'string') : [] })(),
    provider: r.event.provider, funding: r.revision?.funding ?? null, nominal: r.nominalGbp, providerCash: r.cashGbp,
    estimate: r.chargeGbp, held: !!r.hold || r.chargeGbp === null,
  })))
  const sum = (key: 'nominalGbp' | 'cashGbp' | 'chargeGbp') => {
    const known = rows.filter(r => r[key] !== null)
    return { amount: known.length ? known.reduce((total, r) => total + (r[key] ?? BigInt(0)), BigInt(0)) : null, missing: rows.length - known.length }
  }
  const held = report.totals.held, unassigned = rows.filter(r => !r.event.projectId).length
  const pageSize = 50, pageCount = Math.max(1, Math.ceil(rows.length / pageSize)), requested = Number(searchParams.page)
  const page = Math.min(pageCount, Number.isSafeInteger(requested) && requested > 0 ? requested : 1)
  const pageHref = (p: number) => '/costs?' + new URLSearchParams({ month: data.month, project: searchParams.project ?? '', page: String(p) })
  const reportAmount = (value: bigint, known: number, total: number) => `${formatGbpUnits(known ? value : null)}${known > 0 && known < total ? '*' : ''}`
  const visible = rows.slice((page - 1) * pageSize, page * pageSize)
  const quotes = Array.from(new Map(rows.filter(r => r.quote).map(r => [`${r.quote!.currency}:${r.quote!.date}:${r.quote!.source}`, r.quote!])).values())
  const projectGroups = Array.from(new Set(rows.map(r => r.event.projectId))).map(id => ({ id, rows: rows.filter(r => r.event.projectId === id) }))
  const projectName = searchParams.project === 'unassigned' ? 'Unassigned' : data.projects.find(p => p.id === searchParams.project)?.name
  const maxCash = report.daily.reduce((max, row) => row.providerCash > max ? row.providerCash : max, BigInt(0))
  const chatCash = (chat: (typeof report.chats)[number]) => chat.cash === null ? 'Unavailable' : `${formatGbpUnits(chat.cash)}${chat.cashKnown < chat.events ? '*' : ''}`

  return <div className="space-y-7 pb-10">
    <PageHeader title="Project costs" description="A monthly account of estimated client charges and recorded provider usage."><RefreshFigures loadedAt={Date.now()} /><a className={buttonClass} href={'/api/costs/export?' + new URLSearchParams({ month: data.month, project: searchParams.project ?? '' })}>Export source ledger</a></PageHeader>
    <header className="max-w-4xl border-l-4 border-blue-700 pl-5 py-1">
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-800">Monthly cost report · {projectName ?? 'All projects'}</p>
      <h2 className="mt-3 max-w-3xl font-serif text-3xl font-medium tracking-tight text-slate-950 sm:text-4xl">Where usage becomes cost</h2>
      <p className="mt-3 max-w-3xl text-base leading-7 text-slate-600">Estimated client charges are shown alongside provider costs actually recorded against imported usage. Subscription fees remain in Expenses; included usage value is an estimate, never cash paid to a provider.</p>
    </header>
    <form className={`${panel} grid items-end gap-4 sm:grid-cols-[1fr_2fr_auto]`}><label className="text-sm">Month (UTC)<input className={inputClass} type="month" name="month" defaultValue={data.month} /></label><label className="text-sm">Project<select className={inputClass} name="project" defaultValue={searchParams.project ?? ''}><option value="">All projects</option><option value="unassigned">Unassigned</option>{data.projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className={buttonClass}>Apply filters</button></form>
    <div className="rounded-r-xl border border-amber-300 border-l-4 bg-amber-50/80 px-5 py-4 text-sm leading-6 text-amber-950"><strong>Estimates depend on imported records and effective pricing rules.</strong> Coverage can be partial, held records are excluded from estimated charges, and remaining subscription allowance is unknown. A zero provider cash amount may mean usage was included in a subscription; the nominal usage value is not an additional provider payment.</div>
    <section aria-label="Monthly figures" className="grid gap-px overflow-hidden rounded-2xl border border-slate-200 bg-slate-200 sm:grid-cols-2 xl:grid-cols-4">
      {[
        { label: 'Estimated client charges', amount: sum('chargeGbp'), note: 'Policy-based; held items excluded' },
        { label: 'Recorded provider cash', amount: sum('cashGbp'), note: 'Imported per-request / infrastructure costs' },
        { label: 'Nominal usage value', amount: sum('nominalGbp'), note: 'Includes subscription-covered usage value' },
        { label: 'Held from estimate', count: held, note: `${unassigned} unassigned · ${rows.length} usage records` },
      ].map(item => { const detail = 'amount' in item ? item.amount : undefined; return <div key={item.label} className="bg-white px-5 py-5 sm:px-6"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{item.label}</p>{detail ? <p className="mt-3 font-serif text-3xl tabular-nums text-slate-950">{formatGbpUnits(detail.amount)}</p> : <Link href="/costs/review" className="mt-3 block font-serif text-3xl tabular-nums text-slate-950 underline decoration-amber-400 underline-offset-4">{'count' in item ? item.count : '—'}</Link>}<p className="mt-2 text-xs leading-5 text-slate-500">{item.note}{detail && detail.missing > 0 ? ` · ${detail.missing} unavailable` : ''}</p></div>})}
    </section>
    <CostReportCharts daily={report.daily} composition={report.composition} />
    <section className={panel}><div className="border-b border-slate-200 pb-4"><p className="text-xs font-semibold uppercase tracking-widest text-blue-800">Charged conversations</p><h2 className="mt-1 font-serif text-2xl font-medium">Top three chats on each charged day</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-600">Chats are grouped by date, project and conversation ID. Ranking uses known positive estimates; held or unknown events in those conversations remain visible in coverage. Task topics appear only when sanitized source context exists. Same-day commit linkage is not stored.</p></div>{report.chats.length ? <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr><th className="px-3 py-3 text-left">Date</th><th className="px-3 py-3 text-right">Rank</th><th className="px-3 py-3 text-right">Estimate</th><th className="px-3 py-3 text-right">Provider cash</th><th className="px-3 py-3 text-left">Project / conversation / task topics</th><th className="px-3 py-3 text-left">Same-day commit</th></tr></thead><tbody>{Array.from(new Set(report.chats.map(chat => chat.date))).flatMap(date => report.chats.filter(chat => chat.date === date).slice(0, 3).map((chat, i) => <tr key={`${date}:${chat.projectId ?? 'unassigned'}:${chat.conversationId}`} className={i % 2 ? 'bg-slate-50/80' : ''}><td className="px-3 py-3 tabular-nums">{date}</td><td className="px-3 py-3 text-right">{i + 1}</td><td className="px-3 py-3 text-right font-medium tabular-nums">{formatGbpUnits(chat.estimate)}{chat.estimateKnown<chat.events?'*':''}</td><td className="px-3 py-3 text-right tabular-nums">{chatCash(chat)}</td><td className="max-w-md px-3 py-3"><span className="text-xs font-medium text-slate-700">{chat.projectName}</span><code className="mt-1 block break-all text-xs text-slate-600">{chat.conversationId}</code><p className="mt-1 text-xs text-slate-500">{chat.taskTopics.length ? chat.taskTopics.join(' · ') : 'No task topic captured'}</p></td><td className="px-3 py-3 text-xs text-slate-500">No verified commit data</td></tr>))}</tbody></table></div> : <p className="py-8 text-sm text-slate-500">No charged conversations with captured identifiers in this period.</p>}<p className="mt-3 text-xs leading-5 text-slate-500">An asterisk marks partial estimate coverage; it sums known estimated events only. Cash amounts are unavailable unless captured; partial known cash is marked. Commit proximity to usage time would not prove task linkage.</p></section>
    <section className={panel}>
      <div className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-200 pb-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-blue-800">Daily account</p><h2 className="mt-1 font-serif text-2xl font-medium">One line per usage date</h2></div><p className="max-w-lg text-xs leading-5 text-slate-500">Amber dots mark days with provider cash at least 90% of the month’s peak. A day with no imported rows is not evidence of no usage.</p></div>
      {report.daily.length ? <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[740px] text-sm"><thead><tr><th className="px-3 py-3 text-left">Date (UTC)</th><th className="px-3 py-3 text-right">Events</th><th className="px-3 py-3 text-right">Held</th><th className="px-3 py-3 text-right">Nominal value</th><th className="px-3 py-3 text-right">Provider cash</th><th className="px-3 py-3 text-right">Client estimate</th></tr></thead><tbody>{report.daily.map((d, i) => {
        const highCash = d.providerCash > BigInt(0) && d.providerCash * BigInt(10) >= maxCash * BigInt(9)
        return <tr key={d.date} className={i % 2 ? 'bg-slate-50/80' : 'bg-white'}><th className="px-3 py-3 text-left font-medium text-slate-800">{highCash && <span aria-label="High provider cash day" className="mr-2 inline-block h-2 w-2 rounded-full bg-amber-500" />}{d.date}</th><td className="px-3 py-3 text-right tabular-nums">{d.events}</td><td className="px-3 py-3 text-right tabular-nums">{d.held || '—'}</td><td className="px-3 py-3 text-right tabular-nums">{reportAmount(d.nominal,d.nominalKnown,d.events)}</td><td className="px-3 py-3 text-right tabular-nums">{reportAmount(d.providerCash,d.providerCashKnown,d.events)}</td><td className="px-3 py-3 text-right font-semibold tabular-nums">{reportAmount(d.estimate,d.estimateKnown,d.events)}</td></tr>
      })}</tbody><tfoot><tr className="border-t-2 border-slate-300 font-semibold"><th className="px-3 py-3 text-left">Month total</th><td className="px-3 py-3 text-right">{rows.length}</td><td className="px-3 py-3 text-right">{held}</td><td className="px-3 py-3 text-right">{reportAmount(report.totals.nominal,report.totals.nominalKnown,rows.length)}</td><td className="px-3 py-3 text-right">{reportAmount(report.totals.providerCash,report.totals.providerCashKnown,rows.length)}</td><td className="px-3 py-3 text-right">{reportAmount(report.totals.estimate,report.totals.estimateKnown,rows.length)}</td></tr></tfoot></table></div> : <p className="py-10 text-center text-sm text-slate-500">No usage records for this month and filter.</p>}<p className="mt-3 text-xs text-slate-500">An asterisk means some records lack a convertible amount; displayed totals sum the available values only.</p>
    </section>
    <section className={panel}><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-blue-800">Project breakdown</p><h2 className="mt-1 font-serif text-2xl font-medium">Estimated charges by project</h2></div><Link href="/costs/projects" className="text-sm text-blue-700 underline">Manage projects & rates</Link></div>{projectGroups.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{projectGroups.map(group=>{const estimates=group.rows.filter(row=>row.chargeGbp!==null),cash=group.rows.filter(row=>row.cashGbp!==null),total=(items:typeof group.rows,key:'chargeGbp'|'cashGbp')=>items.length?items.reduce((n,row)=>n+(row[key]??BigInt(0)),BigInt(0)):null;const href='/costs?'+new URLSearchParams({month:data.month,project:group.id??'unassigned'});return <Link key={group.id??'unassigned'} href={href} className="rounded-xl border border-slate-200 bg-slate-50/70 p-4 hover:border-blue-200 hover:bg-blue-50/40"><h3 className="font-medium text-slate-900">{group.rows[0].event.project?.name??'Unassigned'}</h3><p className="mt-3 text-xs uppercase tracking-wide text-slate-500">Client estimate</p><p className="font-serif text-2xl tabular-nums">{formatGbpUnits(total(estimates,'chargeGbp'))}{estimates.length<group.rows.length?'*':''}</p><p className="mt-2 text-xs text-slate-600">Provider cash {formatGbpUnits(total(cash,'cashGbp'))}{cash.length<group.rows.length?'*':''} · {group.rows.filter(row=>row.hold||row.chargeGbp===null).length} held · {group.rows.length} records</p></Link>})}</div>:<p className="py-7 text-sm text-slate-500">No project records are available for this month.</p>}<p className="mt-3 text-xs text-slate-500">An asterisk means the sum includes only records with a known amount.</p></section>
    <details id="usage-ledger" className={panel} open={page > 1}><summary className="cursor-pointer font-serif text-xl font-medium">Source usage records</summary><p className="my-3 text-sm text-slate-600">Showing {rows.length ? (page - 1) * pageSize + 1 : 0}–{Math.min(page * pageSize, rows.length)} of {rows.length}. Amounts are converted estimates; source amounts remain available in the export.</p><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{['Time (UTC)', 'Project / provider', 'Funding', 'Nominal value', 'Provider cash', 'Client estimate', 'Review'].map(h => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{visible.map((r, i) => <tr key={r.event.id} className={i % 2 ? 'bg-slate-50/80' : ''}><td className="whitespace-nowrap p-3">{r.event.occurredAt.toISOString().replace('T', ' ').slice(0, 16)}</td><td className="p-3">{r.event.project?.name ?? 'Unassigned'}<p className="text-xs text-slate-500">{r.event.provider} · {r.event.model ?? 'Infrastructure'}</p></td><td className="p-3">{r.revision?.funding ?? 'Unknown'}</td><td className="p-3 text-right tabular-nums">{formatGbpUnits(r.nominalGbp)}{r.revision?.nominalUnits != null && <p className="text-xs text-slate-500">Source {r.revision.currency} {Number(unitsText(r.revision.nominalUnits)).toFixed(2)}</p>}</td><td className="p-3 text-right tabular-nums">{formatGbpUnits(r.cashGbp)}{r.revision?.providerUnits != null && <p className="text-xs text-slate-500">Source {r.revision.currency} {Number(unitsText(r.revision.providerUnits)).toFixed(2)}</p>}</td><td className="p-3 text-right font-medium tabular-nums">{formatGbpUnits(r.chargeGbp)}</td><td className="p-3 text-xs">{r.hold ?? (r.chargeGbp === null ? 'Exchange rate unavailable' : r.policy?.billable ? 'Estimated · not invoiced' : 'Internal / non-billable')}</td></tr>)}</tbody></table></div><nav aria-label="Usage pages" className="mt-4 flex items-center justify-between gap-3 text-sm"><span>Page {page} of {pageCount}</span><div className="flex gap-2">{page > 1 && <Link href={pageHref(page - 1)} className={buttonClass}>Previous</Link>}{page < pageCount && <Link href={pageHref(page + 1)} className={buttonClass}>Next</Link>}</div></nav></details>
    <section className={`${panel} space-y-4`}><div><p className="text-xs font-semibold uppercase tracking-widest text-blue-800">Source coverage</p><h2 className="mt-1 font-serif text-2xl font-medium">Imported data and conversion rates</h2></div><CollectorCoverage/><CsvCoverage/><details className="text-sm"><summary className="cursor-pointer font-semibold">Exchange rates & source amounts</summary><p className="my-3 text-slate-600">{fx.unavailable ? 'Reference service unavailable: stored rates are used where possible; missing conversions remain unavailable.' : 'Daily ECB references are estimates, not bank settlement rates.'} Original source amounts remain in the export.</p><ul className="space-y-1">{quotes.map(q => <li key={`${q.currency}:${q.date}:${q.source}`}>1 {q.currency} = £{q.rate} · {q.date} · {q.source.startsWith('https:') ? <a href={q.source} className="text-blue-700 underline">ECB reference</a> : q.source}</li>)}</ul>{canWrite(user)&&<div className="mt-4"><AnalysisForm action={retainReferenceRates} label="Retain these reference rates"><input type="hidden" name="month" value={data.month}/><input type="hidden" name="project" value={searchParams.project??''}/><p className="text-xs text-slate-500">Keep dated rates for repeatable estimates if the reference service is unavailable later.</p></AnalysisForm></div>}</details></section>
    <LegacyCharges start={data.start} end={data.end} month={data.month} project={searchParams.project} requestedPage={searchParams.legacyPage} usagePage={searchParams.page} />
    <section className={`${panel} text-sm`}><h2 className="font-semibold">How to read this report</h2><div className="mt-3 max-w-4xl space-y-2 leading-relaxed text-slate-700"><p><strong>Provider cash is limited to costs actually imported for usage.</strong> Cursor subscription bills are recorded once in Expenses. Included usage has nominal work value but generally zero additional request cost.</p><p><strong>Estimates follow the saved rate for the usage date.</strong> Missing projects, policies, reliable amounts or exchange rates are held for review. No invoice is created automatically; an estimate is not a payment balance.</p><p><strong>Source coverage is bounded by imported records.</strong> Refresh reloads data already received by Accounts. New Cursor usage arrives through the scheduled collector on your PC.</p><p><strong>Daily proximity does not prove task or commit linkage.</strong> The usage ledger stores provider event identifiers and some sanitized topic context, but it does not store verified source-control commits for these events.</p></div><p className="mt-4"><Link href="/costs/projects" className="text-blue-700 underline">Manage projects and rates</Link> · <Link href="/costs/analysis" className="text-blue-700 underline">Analysis and allocations</Link> · <Link href="/costs/review" className="text-blue-700 underline">Review held usage</Link></p></section>
  </div>
}
