import Link from 'next/link'
import { requireAuth, canWrite } from '@/lib/auth'
import {AnalysisForm} from './analysis/AnalysisForm'
import {retainReferenceRates} from './fx-actions'
import { PageHeader } from '@/components/PageHeader'
import { ledger } from '@/lib/costs/service'
import { ledgerFx, convertUnits, formatGbpUnits } from '@/lib/costs/fx'
import { unitsText } from '@/lib/costs/money'
import { buttonClass, inputClass, panel } from './ui'
import {RefreshFigures} from './RefreshFigures'
export const dynamic = 'force-dynamic'
export default async function CostsPage({searchParams}:{searchParams:{month?:string;project?:string;page?:string}}) {
 const user=await requireAuth()
 const data=await ledger(searchParams.month,searchParams.project),fx=await ledgerFx(data.rows)
 const rows=data.rows.map((r,i)=>({...r,quote:fx.quotes[i],nominalGbp:convertUnits(r.revision?.nominalUnits??null,fx.quotes[i]),cashGbp:convertUnits(r.revision?.providerUnits??null,fx.quotes[i]),chargeGbp:convertUnits(r.charge,fx.quotes[i])}))
 const sum=(items:typeof rows,key:'nominalGbp'|'cashGbp'|'chargeGbp')=>{const known=items.filter(r=>r[key]!==null);return {amount:known.length?known.reduce((s,r)=>s+(r[key]??BigInt(0)),BigInt(0)):null,missing:items.length-known.length}}
 const held=rows.filter(r=>r.hold||r.chargeGbp===null).length,unassigned=rows.filter(r=>!r.event.projectId).length
 const pageSize=50,pageCount=Math.max(1,Math.ceil(rows.length/pageSize)),requested=Number(searchParams.page),page=Math.min(pageCount,Number.isSafeInteger(requested)&&requested>0?requested:1)
 const pageHref=(p:number)=>'/costs?'+new URLSearchParams({month:data.month,project:searchParams.project??'',page:String(p)})
 const groups=Array.from(new Set(rows.map(r=>r.event.projectId))).map(id=>({id,rows:rows.filter(r=>r.event.projectId===id)}))
 const quotes=Array.from(new Map(rows.filter(r=>r.quote).map(r=>[`${r.quote!.currency}:${r.quote!.date}:${r.quote!.source}`,r.quote!])).values())
 const visible=rows.slice((page-1)*pageSize,page*pageSize)
 return <div className="space-y-6">
 <PageHeader title="Project costs" description="Usage value, additional provider charges and estimated client charges in pounds."><RefreshFigures loadedAt={Date.now()}/><a className={buttonClass} href={'/api/costs/export?'+new URLSearchParams({month:data.month,project:searchParams.project??''})}>Export source ledger</a></PageHeader>
 <p className="text-sm leading-relaxed text-slate-600">Saved rates apply automatically to usage on or after their effective date. Refresh figures reloads usage already imported into Accounts. New Cursor usage is collected by the scheduled collector on your PC; this button does not start local collection.</p>
 <form className={`${panel} grid items-end gap-4 sm:grid-cols-[1fr_2fr_auto]`}><label className="text-sm">Month (UTC)<input className={inputClass} type="month" name="month" defaultValue={data.month}/></label><label className="text-sm">Project<select className={inputClass} name="project" defaultValue={searchParams.project??''}><option value="">All projects</option><option value="unassigned">Unassigned</option>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className={buttonClass}>Apply filters</button></form>
 <div className="grid gap-4 md:grid-cols-3">{[
 {title:'Nominal usage value',value:sum(rows,'nominalGbp'),note:'Nominal value of work consumed. Included usage is covered by your subscription.'},
 {title:'Additional provider charges',value:sum(rows,'cashGbp'),note:'Per-request or infrastructure charges imported here. Subscription bills are in Expenses.'},
 {title:'Estimated client charges',value:sum(rows,'chargeGbp'),note:'Your charging policy applied to eligible usage. Not yet invoiced.'}
 ].map(t=><section className={panel} key={t.title}><h2 className="text-sm font-medium text-slate-600">{t.title}</h2><p className="mt-2 text-3xl font-semibold tabular-nums">{formatGbpUnits(t.value.amount)}</p><p className="mt-2 text-sm text-slate-600">{t.note}</p>{t.value.missing>0&&<p className="mt-2 text-sm font-medium text-amber-800">Incomplete · {t.value.missing} records excluded</p>}</section>)}</div>
 <div className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-600"><span><strong>{rows.length}</strong> usage records</span><Link className="font-medium text-amber-800 underline" href="/costs/review">{held} held from client estimates · {unassigned} unassigned</Link><span>Last import: {data.imports[0]?.createdAt.toISOString().replace('T',' ').slice(0,16)??'None'} UTC</span></div>
 <details className={`${panel} text-sm`}><summary className="cursor-pointer font-semibold">How these figures work</summary><div className="mt-4 max-w-3xl space-y-3 leading-relaxed text-slate-700">
 <p><strong>Usage value is not spending.</strong> Included Cursor requests have a nominal value but no additional request charge. The subscription is an actual expense recorded once. See <Link href="/costs/analysis" className="text-blue-700 underline">Analysis & allocations</Link> for recorded costs and margins.</p>
 <p><strong>Client charges use effective-dated rates.</strong> For iTrader, £10 of included usage produces £6 estimated charges: £10 × (50% base + 10 percentage points). £10 of on-demand provider cost produces £11: £10 × (100% + 10%). Infrastructure has its own markup. Internal projects are not charged.</p>
 <p><strong>Held does not mean free.</strong> Missing projects, policies, reliable amounts or exchange rates leave incomplete estimates. Review the reason before billing. Changing historical policies or client links can change estimates. No invoice is created automatically.</p>
 <p><strong>GBP values are converted estimates.</strong> Original amounts stay unchanged. Recorded import rates take precedence; otherwise each usage date uses a historical reference rate, or the preceding published working day. Totals are rounded for display. An actual settled GBP expense takes precedence in profitability reporting.</p>
 <p><strong>Coverage is limited to imported records.</strong> A complete fetched window does not establish coverage of the whole month or subscription cycle. Remaining allowance is unknown. iTrader’s existing ledger remains active.</p></div></details>
 <details className={`${panel} text-sm`}><summary className="cursor-pointer font-semibold">Exchange rates & source amounts</summary><p className="my-3 text-slate-600">{fx.unavailable?'Reference service unavailable: stored rates are used where possible; missing conversions remain unavailable.':'Daily ECB references are estimates, not bank settlement rates.'} Original source amounts remain in the export.</p><ul className="space-y-1">{quotes.map(q=><li key={`${q.currency}:${q.date}:${q.source}`}>1 {q.currency} = £{q.rate} · {q.date} · {q.source.startsWith('https:')?<a href={q.source} className="text-blue-700 underline">ECB reference</a>:q.source}</li>)}</ul>{canWrite(user)&&<div className="mt-4"><AnalysisForm action={retainReferenceRates} label="Retain these reference rates"><input type="hidden" name="month" value={data.month}/><input type="hidden" name="project" value={searchParams.project??''}/><p className="text-xs text-slate-500">Keep dated rates for repeatable estimates if the reference service is unavailable later.</p></AnalysisForm></div>}</details>
 <section className={panel}><div className="mb-4 flex flex-wrap justify-between gap-2"><h2 className="font-semibold">Client charge estimates by project</h2><Link href="/costs/projects" className="text-sm text-blue-700 underline">Manage projects & rates</Link></div>{groups.length?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{groups.map(g=>{const total=sum(g.rows,'chargeGbp');return <Link href={'/costs?'+new URLSearchParams({month:data.month,project:g.id??'unassigned'})} key={g.id??'unassigned'} className="rounded-xl bg-slate-50 p-4 hover:bg-blue-50"><h3 className="font-medium">{g.rows[0].event.project?.name??'Unassigned'}</h3><p className="mt-1 text-xl font-semibold tabular-nums">{formatGbpUnits(total.amount)}</p><p className="mt-1 text-xs text-slate-600">{g.rows.length} records{total.missing?` · ${total.missing} held / unavailable`:''}</p></Link>})}</div>:<p className="text-sm text-slate-600">No records in this period. Import usage or choose another month.</p>}</section>
 <section className={panel}><h2 className="font-semibold">Usage ledger</h2><p className="my-3 text-sm text-slate-600">Showing {rows.length?(page-1)*pageSize+1:0}–{Math.min(page*pageSize,rows.length)} of {rows.length}. Totals include the whole filter.</p><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead><tr>{['Time (UTC)','Project / provider','Funding','Provider charge','Client estimate','Review status'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.event.id}><td className="whitespace-nowrap p-3">{r.event.occurredAt.toISOString().replace('T',' ').slice(0,16)}</td><td className="p-3">{r.event.project?.name??'Unassigned'}<p className="text-xs text-slate-500">{r.event.provider} · {r.event.model??'Infrastructure'}</p></td><td className="p-3">{r.revision?.funding}</td><td className="p-3 tabular-nums">{formatGbpUnits(r.cashGbp)}<p className="text-xs text-slate-500">{r.revision?.currency} {r.revision?.providerUnits==null?'Unknown':Number(unitsText(r.revision.providerUnits)).toFixed(2)}</p></td><td className="p-3 tabular-nums">{formatGbpUnits(r.chargeGbp)}</td><td className="p-3 text-xs">{r.hold??(r.chargeGbp===null?'Exchange rate unavailable':r.policy?.billable?'Estimated · not invoiced':'Internal / non-billable')}</td></tr>)}</tbody></table></div>
 <ul className="divide-y md:hidden">{visible.map(r=><li key={r.event.id} className="space-y-2 py-4"><div className="flex justify-between gap-3"><strong>{r.event.project?.name??'Unassigned'}</strong><span className="shrink-0 font-semibold">{formatGbpUnits(r.chargeGbp)}</span></div><p className="text-xs text-slate-500">{r.event.occurredAt.toISOString().replace('T',' ').slice(0,16)} UTC · {r.revision?.funding}</p><p className="break-words text-sm">{r.event.provider} · {r.event.model??'Infrastructure'}</p><p className="text-xs">Provider charge {formatGbpUnits(r.cashGbp)} · {r.hold??(r.chargeGbp===null?'Exchange rate unavailable':r.policy?.billable?'Estimated client charge':'Internal / non-billable')}</p></li>)}</ul>
 <nav aria-label="Usage pages" className="mt-4 flex items-center justify-between gap-3 text-sm"><span>Page {page} of {pageCount}</span><div className="flex gap-2">{page>1&&<Link href={pageHref(page-1)} className={buttonClass}>Previous</Link>}{page<pageCount&&<Link href={pageHref(page+1)} className={buttonClass}>Next</Link>}</div></nav></section>
 </div>
}
